### ISSUE TITLE
Evitar descargas via CSS

### ISSUE THREAD

**Issue by fzuccolo** [PyAr/CDPedia#249]
Al navegar por CDPedia se descargan íconos desde wikimedia vía CSS. Por ej. navegando en http://localhost:8000/wiki/Argentina los íconos de enlace externo a PDF se obtienen mediante:

```css
#bodyContent a[href$=".pdf"].external {
    background: url(http://upload.wikimedia.org/wikipedia/commons/2/23/Icons-mini-file_acrobat.gif);
}
```

Hay varios enlaces como estos en `resources/skins/css` que descargan íconos externos, deberíamos sacarlos o pedir una imágen local.
